name: Commit Stage
run-name: Commit Stage - ${{ github.ref }}

on:
  push:
    branches:
      - '*'

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  # ------------------------------- Application + Cache Setup ------------------------------- #
  build:
    runs-on: ubuntu-22.04
    name: Build Application
    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        id: dependencies
        run: npm ci

      - name: Build
        id: build
        run: npm run build

  # ------------------------------- Unit Tests ------------------------------- #
  test:
    runs-on: ubuntu-22.04
    name: Unit Tests
    needs: build
    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

  # ------------------------------- Static Analysis ------------------------------- #
  analyze:
    runs-on: ubuntu-22.04
    name: Static Analysis
    needs: build
    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Lint
        run: npm run lint
